@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "server.Server",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1113075967 { 
   	label=clientHandler
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ClientHandlerSerialize1012717164[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClientHandlerSerialize</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fabric: ServerMessageFabric [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   in: ObjectInputStream [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   messageHandler: MessageHandler [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   out: ObjectOutputStream [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   sender: Sender [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   server: Server [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   session_id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   socket: Socket [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   toSendQueue: BlockingQueue&lt;ObjectServer&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userListener: UserListener [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ send(msg: ObjectServer)</TD></TR>
<TR><TD ALIGN="LEFT" >+ shutdown()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MessageHandler1012717164[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MessageHandler</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fabric: ServerMessageFabric [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   queue: BlockingQueue&lt;ObjectServer&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ handle(request: ObjectUser)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1082500464 { 
   	label=ClientHandlerSerialize
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Sender1707046309[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Sender</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserListener1707046309[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserListener</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_1488192283 { 
   	label=factory
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   HandlerFactory2024040784[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HandlerFactory</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ doMakeHandler(impl: Implementations, socket: Socket, server: Server, id: int): ClientHandler</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

subgraph cluster_1779040354 { 
   	label=serverObject
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1130615652 { 
   	label=serialization
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ErrorAnswerServerSerialized488773510[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ErrorAnswerServerSerialized</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getResponseData()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

MessageFromUserSerialized488773510[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)MessageFromUserSerialized</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

SuccessAnswerServerSerialized488773510[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SuccessAnswerServerSerialized</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   succeedRequestId: long [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getResponseData()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_266031025 { 
   	label=fabric
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ServerSerializedFabric570874021[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ServerSerializedFabric</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ makeDetachedUser(): DetachedUserServer</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeErrorAnswer(): ErrorAnswerServer</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeServerMessage(): ServerMessageFabric</TD></TR>
<TR><TD ALIGN="LEFT" >+ makeSuccessAnswer(succeedId: long): SuccessAnswerServer</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

subgraph cluster_1821959325 { 
   	label=Server
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   ServerConfiguration340823954[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ServerConfiguration</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   implementation: Implementations [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   port: int [1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ implementation(): Implementations</TD></TR>
<TR><TD ALIGN="LEFT" >+ port(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_905826493 { 
   	label=server
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Server905826493[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Server</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   clientHandlers: List&lt;ClientHandler&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   configuration: ServerConfiguration [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   handlerFactory: HandlerFactory [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   socket: ServerSocket [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- closeSocket()</TD></TR>
<TR><TD ALIGN="LEFT" >+ doBroadcast(msg: ObjectServer)</TD></TR>
<TR><TD ALIGN="LEFT" >- readConfig(path: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ run()</TD></TR>
<TR><TD ALIGN="LEFT" >+ shutdown()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

'edges    
ClientHandlerSerialize1012717164 -> MessageHandler1012717164[label="messageHandler
[0..1]"];
ClientHandlerSerialize1012717164 -> Sender1707046309[label="sender
[0..1]"];
ClientHandlerSerialize1012717164 -> Server905826493[label="server
[0..1]"];
ClientHandlerSerialize1012717164 -> ServerSerializedFabric570874021[arrowhead=none];
ClientHandlerSerialize1012717164 -> UserListener1707046309[label="userListener
[0..1]"];
MessageHandler1012717164 -> ErrorAnswerServerSerialized488773510[label="getResponseData() -> getResponseData()", arrowhead=none];
MessageHandler1012717164 -> MessageFromUserSerialized488773510[arrowhead=none];
MessageHandler1012717164 -> SuccessAnswerServerSerialized488773510[label="getResponseData() -> getResponseData()", arrowhead=none];
Server905826493 -> ClientHandlerSerialize1012717164[arrowhead=none];
Server905826493 -> ClientHandlerSerialize1012717164[label="clientHandlers
[0..*]", arrowhead=none];
Server905826493 -> HandlerFactory2024040784[label="handlerFactory
[0..1]"];
Server905826493 -> ServerConfiguration340823954[label="configuration
[0..1]"];
UserListener1707046309 -> MessageHandler1012717164[label="run() -> handle()"];
    
}
@enduml